apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: swagger-api-konfig
  env:
    - name: FRONTEND_LOCATION
      value: https://status.nav.no/sp
    - name: statusholder_url
      value: https://statusholder.prod-fss-pub.nais.io
    - name: BACKEND_LOCATION
      value: https://status-api.nav.no
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
  replicas:
    min: 2
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  ingresses:
    - https://status-api.nav.no
  gcp:
    sqlInstances:
      - name: navstatus
        type: POSTGRES_12
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: navstatus
            envVarPrefix: DB
  azure:
    application:
      allowAllUsers: true
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
        - application: portal
          namespace: navdig
          cluster: prod-gcp
        - application: statuspoll
          namespace: navdig
          cluster: prod-gcp
        - application: promstatusproxy
          namespace: navdig
          cluster: prod-gcp
    outbound:
      external:
        - host: statusholder.prod-fss-pub.nais.io