apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: statusplattform-server
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: swagger-api-konfig
  replicas:
    {{#if min_replicas}}min: {{min_replicas}}{{/if}}
    {{#if max_replicas}}max: {{max_replicas}}{{/if}}
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  gcp:
    sqlInstances:
      - name: navstatus
        type: POSTGRES_12
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: navstatus
            envVarPrefix: DB
  azure:
    application:
      allowAllUsers: true
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
        - application: portal
          namespace: navdig
        - application: statuspoll
          namespace: navdig
        - application: promstatusproxy
          namespace: navdig
        - application: onpremstatuspoll
          namespace: navdig
          cluster: "{{ spec.env.ENV }}-fss"
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
  env:
    - name: teamkatalogApiUrl
      value: http://team-catalog-backend.org.svc.cluster.local
    {{#each spec.env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
  ingresses:
    {{#each spec.ingresses as |url|}}
    - {{url}}
    {{/each}}
