openapi: 3.0.3
info:
  description: Documentation Nav portal REST API
  version: '0.1'
  title: Nav REST API
servers:
  - url: /rest
paths:
  /Dashboards:
    get:
      tags:
        - Dashboard
      summary: Hent alle dashboard,
      description: Henter id og navn på alle dashboard. Ikke tilhørende områder/tjenester.
      operationId: getDashboards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dashboard'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
  /Dashboard:
    post:
      tags:
        - Dashboard
      summary: Legg til nytt dashboard.
      description: Legg til nytt dashboard. Id genereres i backend, og sendes tilbake
      operationId: addDashboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dashboard'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: uuid
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /Dashboard/{Dashboard_id}:
    put:
      tags:
        - Dashboard
      summary: Legg inn/ fjern/ endre rekkefølge på områder på dashbord
      description: Legg inn liste av område-ider som hører til på dashboardet. Første id vil komme først osv.
      operationId: putDashboards
      parameters:
        - name: Dashboard_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          'application/json':
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
    get:
      tags:
        - Dashboard
      summary: Hent dashboard med innhold.
      description: henter et dashboard med alle underliggende områder/ tjenester
      operationId: getDashboard
      parameters:
        - name: Dashboard_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dashboard'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /Areas/{Dashboard_id}:
    get:
      tags:
        - Area
      summary: Alle områder
      operationId: AreasOnDashBoard
      description: Henter alle områder med underliggende tjenster
      parameters:
        - name: Dashboard_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
  /Areas:
    get:
      tags:
        - Area
      summary: Alle områder
      operationId: Area
      description: Henter alle områder med underliggende tjenster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
    post:
      tags:
        - Area
      summary: Legg til ett nytt område
      requestBody:
        description: Legg til ett nytt område. Her trenger IKKE services å være med ved innsending.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Area'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }

  /Area/{Area_id}/{Service_id}:
    put:
      tags:
        - Area
      summary: ServiceOnArea
      description: Legg til en ny tjeneste på et område
      parameters:
        - name: Area_id
          in: path
          required: true
          schema:
            type: string
        - name: Service_id
          in: path
          required: true
          schema:
            type: string

      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
    delete:
      tags:
        - Area
      summary: ServiceOnArea
      description: Fjern tjeneste fra område
      parameters:
        - name: Area_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: Service_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Deletead
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
  /Area/{Area_id}:
    delete:
      tags:
        - Area
      summary: Fjern område
      description: Fjern område
      parameters:
        - name: Area_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Deletead
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
  /Services/Typer:
    get:
      tags:
        - Service
      summary: Hent alle tjenester typer
      operationId: Service
      description: Henter alle servicer med tjenesteavhengigheter - ett lag dypt.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Applikasjon
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
  /Services:
    get:
      tags:
        - Service
      summary: Hent alle tjenester
      operationId: Service
      description: Henter alle servicer med tjenesteavhengigheter - ett lag dypt.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
  /Service:
    post:
      tags:
        - Service
      summary: Legg til tjeneste
      requestBody:
        description: Legg til en ny tjeneste
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Deleted
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
  /Service/{Service_id}:
    delete:
      tags:
        - Service
      summary: Slett en tjeneste
      parameters:
        - name: Service_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: Deleted
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }

  /ServiceStatus:
    post:
      tags:
        - Record
      summary: Legg til status på en tjeneste
      requestBody:
        description: Legg til status på en tjeneste
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Deleted
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
  /Service/{Service_id}/{DependentOnService_id}:
    put:
      tags:
        - Area
      summary: Service dependency
      description: Legg til en tjenesteavhengigheter.
      parameters:
        - name: Service_id
          in: path
          required: true
          schema:
            type: string
        - name: DependentOnService_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }



components:
  schemas:
    Dashboard:
      title: Dashboard
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: "84e49ba0-7409-41ed-8ebe-949ad94dc1d3"
        name:
          type: string
          example: "Privatperson"
        areas:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/Area'
    ServiceToArea:
      title: ServiceToArea
      type: object
      properties:
        areaId:
          type: string
          format: uuid
        serviceId:
          type: string
          format: uuid
    Area:
      title: Area
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
          readOnly: true
        descripiton:
          type: string
        icon:
          type: string
        services:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/Service'
        status:
          readOnly: true
          $ref: '#/components/schemas/Status'
      required:
        - name
    Service:
      title: Service
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
          readOnly: true
        type:
          $ref: '#/components/schemas/ServiceType'
        team:
          type: string
        dependencies:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/Service'
        monitorlink:
          type: string
        description:
          type: string
        logglink:
          type: string
        status:
          $ref: '#/components/schemas/Status'
    ServiceStatus:
      title: ServiceStatus
      type: object
      properties:
        serviceId:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/Status'

    Status:
      type: string
      enum:
        - OK
        - ISSUE
        - DOWN
    ServiceType:
      type: string
      enum:
        - APPLIKASJON
        - TJENESTE
