apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: swagger-api-konfig
  replicas:
    min: 1
    max: 1
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  gcp:
    sqlInstances:
      - name: navstatus-dev
        type: POSTGRES_17
        tier: db-g1-small
        databases:
          - name: navstatusdev
            envVarPrefix: DB

  azure:
    application:
      allowAllUsers: true
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
        - application: portal
        - application: statuspoll
        - application: promstatusproxy
        - application: onpremstatuspoll
          cluster: "{{ spec.env.ENV }}-fss"
        - application: statusplattform-nais-operator
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
  env:
    - name: teamkatalogApiUrl
      value: https://teamkatalog-api.intern.nav.no
    - name: FRONTEND_LOCATION
      value: https://status.dev.nav.no
    - name: statusholder_url
      value: https://statusholder.dev-fss-pub.nais.io
    - name: TENANT
      value: trygdeetaten.no
    - name: ENV
      value: dev
      # Used by app for conditional logic
    - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
      value: "5"
    - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
      value: "1"
    - name: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
      value: "60000"
    - name: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
      value: "300000"
  ingresses:
    - https://status-api.intern.dev.nav.no
