apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: swagger-api-konfig
    {{#if azure_envfrom}}
    - secret: azure-app
    {{/if}}

  initContainers:
    - name: wait-for-db
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Waiting for Cloud SQL proxy on 127.0.0.1:5432 ..."
          for i in $(seq 1 180); do
            nc -z 127.0.0.1 5432 && echo "DB is up" && exit 0
            sleep 1
          done
          echo "DB not reachable on 127.0.0.1:5432" >&2
          exit 1

  replicas:
    {{#if min_replicas}}min: {{min_replicas}}{{/if}}
    {{#if max_replicas}}max: {{max_replicas}}{{/if}}
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  gcp:
    {{#unless sql_disabled}}
    sqlInstances:
      - name: navstatus
        type: POSTGRES_17
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: navstatus
            envVarPrefix: DB
    {{/unless}}

  {{#unless azure_disabled}}
  azure:
    application:
      allowAllUsers: true
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  {{/unless}}

  accessPolicy:
    inbound:
      rules:
        - application: portal
        - application: statuspoll
        - application: promstatusproxy
        - application: onpremstatuspoll
          cluster: "{{ spec.env.ENV }}-fss"
        - application: statusplattform-nais-operator
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
  env:
    - name: teamkatalogApiUrl
      value: http://team-catalog-backend.org.svc.cluster.local
    {{#each spec.env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
  ingresses:
    {{#each spec.ingresses as |url|}}
    - {{url}}
    {{/each}}
